### PR TITLE
Updated website text

### PR DESCRIPTION
**Pull request by PrJared**
I'm not sure where each section of text goes on the website.  There seems to be a lot of duplication.

### CODE REVIEW

**Comment by imasaru** [comment]
@PrJared Learn More, Live More, Love More 😄 🙏

**Comment by VitalikL** [comment]
Thanks @PrJared for the contribution. However there are numerous issues with the PR:

1. Meta tags have maximum length (e.g description).
2. There are heavy modifications regarding us in terms of status and relationship towards GC. We are not affiliated and we must keep it that way. We can mention that we are functioning as a supporting ministry
3. Since the text is not just typo edit, I will close this PR and make necessary typo changes separately.

**Comment by PrJared** [comment]
1. Ok, just tell me what the maximum length is.

2. Stating that "we are not affiliated with the GC" makes it sound suspect, like we're trying to do our own thing while leeching their lessons.  We are all members of the SDA Church, and I think that is all that needs to be said.

**Comment by PrJared** [comment]
we also need to use the phrase "Digital Discipleship" because that's a buzzword in the Adventist church at the moment.

**Pull request closed without merging**
